db-uri = "postgres://authenticator:authenticator@127.0.0.1:54329/afg_registry"
db-schemas = "public"
db-anon-role = "anon"
db-pool = 10
server-host = "0.0.0.0"
server-port = 54321
server-cors-allowed-origins = "*"
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
db-max-rows = 200
db-prepared-statements = true
db-plan-enabled = false
